auto: true

#markdown: rdiscount
markdown: kramdown
#markdown: redcarpet
#pygments: true
highlighter: rouge
paginate: 8
permalink: /:year-:month-:day/:title.html
#permalink: /:title
#permalink: pretty

